updates

diff --git a/jobs/export_dashboard/templates/bin/errand.sh.erb b/jobs/export_dashboard/templates/bin/errand.sh.erb
--- a/jobs/export_dashboard/templates/bin/errand.sh.erb
+++ b/jobs/export_dashboard/templates/bin/errand.sh.erb
@@ -1,16 +1,19 @@
 #!/bin/bash
-set -e
-set -u
 
+set -e # exit immediately if a simple command exits with a non-zero status
+set -u # report the usage of uninitialized variables
+
+# Directory to store the Docker execution files
 export PATH=$PATH:/var/vcap/packages/docker/bin
 
+# Directory to store the Export errand files
 export JOB_DIR=/var/vcap/jobs/export_dashboard
 
 # Directory to store the Docker configuration files
 export DOCKER_CONF_DIR=${JOB_DIR}/config
 
 <% if_p('remote-docker.tls_cacert') do |tls_cacert| %>
-# Trust only remotes providing a certificate signed by the CA given here
+# Path to TLS CA certificate file
 export DOCKER_TLS_CACERT="--tlscacert=${DOCKER_CONF_DIR}/docker.cacert"
 <% end %>
 
@@ -24,19 +27,26 @@ export DOCKER_TLS_CERT="--tlscert=${DOCKER_CONF_DIR}/client.cert"
 export DOCKER_TLS_KEY="--tlskey=${DOCKER_CONF_DIR}/client.key"
 <% end %>
 
+# Elasticsearch hostname / IP address
 ES_HOST='<%= p("elasticsearch.host") %>'
+
+# Elasticsearch port number
 ES_PORT='<%= p("elasticsearch.port") %>'
+
+# Docker hostname / IP address
 <% p('remote-docker.host').each do |host| %>
 DOCKER_HOST='<%= host %>'
 <% end %>
+
+# Docker port number
 DOCKER_PORT='<%= p("remote-docker.port") %>'
 
+# Epoch value
 N=`date +%s`
 
+# Command to export the dashboards, visualization and searches
 docker -D -H $DOCKER_HOST:$DOCKER_PORT --tlsverify ${DOCKER_TLS_CACERT:-} ${DOCKER_TLS_CERT:-} ${DOCKER_TLS_KEY:-} run -v /var/vcap/store/dashboards:/opt/dashboards --rm -i taskrabbit/elasticsearch-dump \
     --input=http://$ES_HOST:$ES_PORT/.kibana \
     --output=/opt/dashboards/kibana-exported.$N.json  \
     --type=data \
     --searchBody='{"filter": { "or": [ {"type": {"value": "dashboard"}}, {"type" : {"value":"visualization"}}, {"type" : {"value":"search"}}] }}'
-
-
